"""Pure Markdown renderer for benchmark results (S-090).

No I/O, no ``datetime.now()`` (injected ``date``) so the drift test is
stable. Single source of truth for the published benchmark table.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from seerflow.launch.benchmark import BenchmarkResult

_REPRODUCE = "python -m seerflow.launch.benchmark --count 20000 --markdown"


def render_benchmark_report(result: BenchmarkResult, *, date: str) -> str:
    """Render ``result`` as deterministic Markdown."""
    rss = "n/a" if result.peak_rss_mb is None else f"{result.peak_rss_mb:,.1f}"
    return "\n".join(
        (
            "## Seerflow Benchmark Results",
            "",
            f"_Generated {date}. Measured on commodity hardware against a "
            "synthetic syslog workload through the full pipeline (parse + "
            "Drain3 + entity resolution + ML ensemble + Sigma + SQLite "
            "persistence). Numbers are hardware-dependent -- reproduce with "
            "the command below; your numbers will differ._",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Events processed | {result.event_count:,} |",
            f"| Wall time | {result.elapsed_s:.3f} s |",
            f"| Throughput | {result.throughput_eps:,.0f} events/sec |",
            f"| Latency p50 | {result.latency_p50_ms:.3f} ms/event |",
            f"| Latency p95 | {result.latency_p95_ms:.3f} ms/event |",
            f"| Latency mean | {result.latency_mean_ms:.3f} ms/event |",
            f"| Peak RSS | {rss} MB |",
            f"| Alerts raised | {result.alerts:,} |",
            "",
            "### Reproduce",
            "",
            "```bash",
            _REPRODUCE,
            "```",
            "",
            "### Detection quality",
            "",
            "Throughput is only half the story. Detection quality "
            "(precision / recall / F1 / false-positive rate) is validated "
            "separately against a synthetic LANL subset -- see the "
            "**Validation** section of the README, regenerated by "
            "`python -m seerflow.lanl.report` (owned by S-088, not "
            "recomputed here).",
            "",
        )
    )
